version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: clients
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: clients

	clients:
		build: .
		image: chamaconekt/clients
		links:
		- postgres
		container_name: clients
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- clients
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/clients-nginx/nginx.conf
		depends_on:
			- clients
		ports:
			- 80:80
		volumes_from:
			- clients

volumes:
	clients-static-files:
		driver:local